# Generated by Django 5.1.3 on 2024-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='gender', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.EmailField(default='yourmail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='yourmail@gmail.com', max_length=50),
        ),
    ]
