# Generated by Django 5.1.3 on 2024-11-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0005_alter_student_mail_alter_student_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tid',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='gender', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.EmailField(default='mail', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(default='123456778'),
            preserve_default=False,
        ),
    ]
