# Generated by Django 5.1.3 on 2024-11-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0009_alter_student_password_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.CharField(max_length=10000),
        ),
    ]
