# Generated by Django 5.1.3 on 2024-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0014_alter_teacher_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='lapp.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='lapp.course'),
        ),
    ]
