# Generated by Django 5.1.3 on 2024-12-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0015_alter_assignment_students_alter_teacher_courses'),
    ]

    operations = [
    ]
