# Generated by Django 5.1.3 on 2024-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0016_auto_20241206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='lapp.course'),
        ),
    ]
